<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Kontur.Core</RootNamespace>
    <AssemblyName>Kontur.Core</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- ВАЖНО: здесь не должно появиться ни одной ссылки на GodotSharp. -->
  </PropertyGroup>

</Project>
